project:
  type: website

website:
  title: "Barcode Beats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bios.qmd
        text: Meet the Team
      - href: fpga.qmd
        text: FPGA Design
      - href: mcu.qmd
        text: MCU Design
      - href: calculations.qmd
        text: Relevant Equations
      - href: documentation.qmd
        text: Documentation
      - href: results.qmd
        text: Results
      - href: more.qmd
        text: More

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



